### ISSUE TITLE
[Twitter] Url not valid

### ISSUE THREAD

**Issue by qlaffont** [mastermunj/username-checker#82]
For twitter service : 
- url who should be returned : `https://twitter.com/qlaffont`
- url returned : `https://api.twitter.com/i/users/username_available.json?username=qlaffont`

**Comment by mastermunj** [comment]
Oh yes, I have been planning to work on separating the URL for checking the availability and the actual profile URL.

Hopefully, soon I will be able to pick this up.

**Comment by qlaffont** [comment]
https://github.com/mastermunj/username-checker/pull/91
